<?php
$query = $this->params()->fromQuery();
$sortByQuery = 'dcterms:date';
$sortOrderQuery = 'desc';
if (array_key_exists("sort_by", $query) && $query["sort_by"]) {
    $sortByQuery = $query["sort_by"];
}
if (array_key_exists("sort_order", $query) && $query["sort_order"]) {
    $sortOrderQuery = $query["sort_order"];
}
?>

<li>
    <button
        class="dropdown-item <?php echo ($sortByQuery === 'created' && $sortOrderQuery === 'desc') ? 'fw-bold disabled' : ''; ?>"
        data-sort_by="created" data-sort_order="desc">Recently
        Added</button>
</li>
<li>
    <button
        class="dropdown-item <?php echo ($sortByQuery === 'dcterms:date' && $sortOrderQuery === 'desc') ? 'fw-bold disabled' : ''; ?>"
        data-sort_by="dcterms:date" data-sort_order="desc">Newest
        to Oldest</button>
</li>
<li>
    <button
        class="dropdown-item <?php echo ($sortByQuery === 'dcterms:date' && $sortOrderQuery === 'asc') ? 'fw-bold disabled' : ''; ?>"
        data-sort_by="dcterms:date" data-sort_order="asc">Oldest
        to Newest</button>
</li>
<li>
    <button
        class="dropdown-item <?php echo ($sortByQuery === 'dcterms:title' && $sortOrderQuery === 'asc') ? 'fw-bold disabled' : ''; ?>"
        data-sort_by="dcterms:title" data-sort_order="asc">Title
        (a to z)</button>
</li>
<li>
    <button
        class="dropdown-item <?php echo ($sortByQuery === 'dcterms:title' && $sortOrderQuery === 'desc') ? 'fw-bold disabled' : ''; ?>"
        data-sort_by="dcterms:title" data-sort_order="desc">Title
        (z to a)</button>
</li>