<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>


<?php
$this->htmlElement('body')->appendAttribute('class', 'resource search');
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('escapeHtml');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$api = $this->plugin('api');
$this->headScript()
  ->appendFile($this->assetUrl('js/search.js', 'Search'));
// this is currently only set up to search items
if (isset($response)):
  $totalResults = $response->getResourceTotalResults('items');
  $results = $response->getResults('items');
?>

  <div class="container pt-2 pb-4 pb-md-5" id="grid-container">
    <div class="row" id="grid-header">
      <div class="col px-sm-5">
        <div class="row align-items-center mb-3 mb-sm-2 mb-md-1">
          <div class="col-auto">
            <div class="page-title">
              <?php echo $this->pageTitle($translate('Search'), 2); ?>
            </div>
          </div>
          <div class="col-auto">
            <?php if ($facets): ?>
              <?php
              $hasFacets = false;
              foreach ($facets as $key => $value) {
                if ($value) {
                  $hasFacets = true;
                }
              }
              ?>
              <?php if ($hasFacets): ?>
                <!-- filter  -->
                <button id="filter-button" class="btn btn-fit-pink floating-action icon-only" type="button"
                  data-bs-toggle="offcanvas" data-bs-target="#searchFilters" aria-controls="searchFilters"
                  aria-label="Filter results">
                  <span class="action-container">
                    <i class="fas fa-filter" aria-hidden="true" title="Filter results">
                    </i>
                  </span>
                </button>
                <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="searchFilters"
                  aria-labelledby="searchFiltersLabel">
                  <div class="offcanvas-header border-bottom">
                    <h3 class="offcanvas-title" id="searchFiltersLabel">
                      <?php echo $translate('Search Filters'); ?>
                    </h3>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                  </div>
                  <div class="offcanvas-body p-0">
                    <?php echo $this->partial('search/facets', ['facets' => $facets, 'dateFacetStats' => $dateFacetStats, 'queryParams' => $this->params()->fromQuery()]); ?>
                  </div>
                </div>
              <?php endif; ?>
            <?php endif; ?>
          </div>
          <div class="w-100 d-sm-none"></div>
          <div class="col-auto ms-sm-auto mt-3">
            <div class="card rounded-0 border border-2 border-black">
              <div class="card-body p-2 p-sm-3 p-md-4 fw-bold">
                Showing
                <?php echo number_format($totalResults); ?>
                <?php echo ($totalResults == 1) ? ' result' : ' results'; ?>
                <?php if (($totalResults > 0) && (count($sortOptions) > 1)): ?>
                  <div class="d-inline-block ms-2">
                    <button class="border-0 bg-transparent p-0" type="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
                      <i class="fas fa-sort"></i>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end rounded-0 border border-2 border-black" id="sort-dropdown">
                      <?php
                      $currentSort = $query->getSort();
                      foreach ($sortOptions as $value => $sortOptionLabel):
                      ?>
                        <li>
                          <button class="dropdown-item <?php echo ($currentSort == $value) ? 'fw-bold disabled' : ''; ?>"
                            data-sort="<?php echo $value; ?>">
                            <?php echo $sortOptionLabel; ?>
                          </button>
                        </li>
                      <?php endforeach; ?>
                    </ul>
                  </div>
                <?php endif; ?>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-3 mt-sm-2 mt-md-1">
          <div class="col-auto">
            <?php echo $this->QueryToStringHelper($this->params()->fromQuery(), $this->params()->fromRoute(), $this->searchForm()); ?>
          </div>
        </div>
      </div>
    </div>
    <?php $this->trigger('view.browse.before'); ?>
    <?php if ($totalResults > 0): ?>
      <div class="row">
        <div class="col px-sm-5">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xxl-5 align-items-center" id="grid">
            <?php
            foreach ($results as $result):
              // Need to make sure the item actually exists because it can show up in the index a few minutes after it's been deleted         
              try {
                $item = $api->read('items', $result['id'])->getContent();
              } catch (Omeka\Api\Exception\NotFoundException $e) {
                $item = null;
              }
            ?>
              <?php
              if ($item):
                $heading = $item->displayTitle(null, ($filterLocale ? [$lang, ''] : null));
              ?>
                <div class="col grid-item-container">
                  <div class="card border-0 grid-item">
                    <?php echo $item->linkRaw($this->thumbnail($item, 'medium', ['class' => 'w-100', 'alt' => $heading]), null, ['class' => 'card-img', 'title' => $heading]); ?>
                    <div class="card-body">
                      <h3 class="grid-item-title">
                        <?php echo $item->link($heading, null, ['class' => 'text-dark text-decoration-none', 'title' => $heading]); ?>
                      </h3>
                    </div>
                  </div>
                </div>
              <?php endif; ?>
            <?php endforeach; ?>
          </div>
        </div>
      </div>
      <?php $this->trigger('view.browse.after'); ?>
      <div class="row justify-content-center pagination-row d-none">
        <div class="col-auto">
          <?php echo $this->pagination(); ?>
        </div>
      </div>
    <?php else: ?>
      <div class="row">
        <div class="col px-sm-5">
          <p class="lead">
            <?php echo $translate('We\'re sorry, but your search did not return any results. Please try searching again, or browsing through the items or collections.'); ?>
          </p>
        </div>
      </div>

    <?php endif; ?>
  </div>
<?php else: ?>
  <div class="container pt-2 pb-4 pb-md-5" id="grid-container">
    <div class="row" id="grid-header">
      <div class="col px-sm-5">
        <div class="row align-items-center mb-3 mb-sm-2 mb-md-1">
          <div class="col-auto">
            <div class="page-title">
              <?php echo $this->pageTitle($translate('Search'), 2); ?>
            </div>
          </div>
        </div>
        <div class="row mt-3 mt-sm-2 mt-md-1">
          <div class="col-auto">
            <?php echo $this->QueryToStringHelper($this->params()->fromQuery(), $this->params()->fromRoute(), $this->searchForm()); ?>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col px-sm-5">
        <p class="lead">
          We're sorry, but there was an error during your search. Please try searching again, or browsing through the
          items or collections. Please contact us at <a
            href="mailto:archiveondemand@fitnyc.edu">archiveondemand@fitnyc.edu</a> if you continue to run into trouble.
        </p>
        <p>
          <?php echo $this->messages(); ?>
        </p>
      </div>
    </div>
  </div>

<?php endif; ?>